InstaGrab/website/models.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from . import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    email = db.Column(db.String(100))
    password = db.Column(db.String(100))
    cookies = db.Column(db.String(5000))

class UsernameList(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    listname = db.Column(db.String(100))
    list = db.Column(db.String(50000))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

InstaGrab/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path

db = SQLAlchemy()

def create_app():

    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    app.config['SECRET_KEY'] = 'juguyjtjhg'
    db.init_app(app)

    from .models import User, UsernameList
    with app.app_context():
        db.create_all()
        ### a supprimer
        '''import json
        dummyUser = User(username='foobar', email='foobar@gmail.com', password='fooBar_1234')
        dummyList1 = UsernameList(user_id=1, listname='list1', list=json.dumps(['user1', 'user2', 'user3']))
        dummyList2 = UsernameList(user_id=1, listname='list2', list=json.dumps(['insta_user', 'another_user']))
        dummyList3 = UsernameList(user_id=1, listname='list3', list=json.dumps(['cool_insta', 'awesome_user', 'insta_lover']))
        dummyList4 = UsernameList(user_id=1, listname='list4', list=json.dumps(['fashion_insta', 'style_guru']))
        dummyList5 = UsernameList(user_id=1, listname='list5', list=json.dumps(['foodie_insta', 'yummy_user', 'chef_master']))
        db.session.add(dummyUser)
        db.session.add(dummyList1)
        db.session.add(dummyList2)
        db.session.add(dummyList3)
        db.session.add(dummyList4)
        db.session.add(dummyList5)
        db.session.commit()'''
        ###

    from .routes import routes

    app.register_blueprint(routes, url_prefix='/')

    return app

InstaGrab/website/routes.py
from flask import Blueprint, render_template, redirect, request, url_for, flash, session

import json

from .models import User, UsernameList
from . import db
from .automation import Auto


routes = Blueprint('routes', __name__)

@routes.route('/')
def home():
    return render_template('home.html', active_page='home')

@routes.route('/toolhub')
def toolHub():
    if 'user' in session:
        currentUser = User.query.filter_by(username=session['user']).first()
        usernameLists = UsernameList.query.filter_by(user_id=currentUser.id).all()
        data = []
        for uList in usernameLists:
            data.append({'id': uList.id, 'name':uList.listname, 'usernames': json.loads(uList.list)})
        return render_template('toolhub.html', active_page='toolhub', data=data)
    else:
        flash('You need to login to access this page.', category='error')
        return redirect(url_for('routes.login'))
    
@routes.route('/login', methods=['GET', 'POST'])
def login():
    if 'user' in session:
        flash('You are already logged in !', category='error')
        return redirect(url_for('routes.toolHub'))
    elif request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        user = User.query.filter_by(username=username).first()

        auto = Auto()
        if user:
            auto.loadCookies(json.loads(user.cookies))
            auto.refresh()
            if auto.isLogged():
                flash('Logged in successfully, welcome back !', category='success')
                session['user'] = username
                auto.quit()
                return redirect(url_for('routes.toolHub'))
            else:
                auto.login(username, password)
                cookies = auto.getCookies()
                user.cookies = json.dumps(cookies)
                session['user'] = username
                flash('Logged in successfully, welcome back !', category='success')
                auto.quit()
                return redirect(url_for('routes.toolHub'))
        else:
            auto.login(username, password)
            if auto.isLogged():
                cookies = auto.getCookies()
                new_user = User(username=username, password = password, cookies = json.dumps(cookies))
                db.session.add(new_user)
                db.session.commit()
                session['user'] = username
                flash('Logged in successfully!', category='success')
                auto.quit()
                return redirect(url_for('routes.toolHub'))
            else:
                flash('Username or e-mail is incorrect, try again', category='error')
                auto.quit()
                return render_template('login.html')
    else:
        return render_template('login.html', active_page='login')

@routes.route('/logout')
def logout():
    if 'user' in session:
        session.pop('user', None)
        flash('Logged out successfully !', category='success')
        return redirect(url_for('routes.home'))
    else:
        flash('You are already logged out', category='error')
        return redirect(url_for('routes.home'))
    
@routes.route('/newlist', methods=['POST'])
def newList():
    listName = request.form['listname']
    currentUser = User.query.filter_by(username=session['user']).first()
    newlist = UsernameList(user_id=currentUser.id, listname=listName, list=json.dumps([]))
    db.session.add(newlist)
    db.session.commit()
    return redirect(url_for('routes.toolHub'))

@routes.route('/deletelist', methods=['POST'])
def deleteList():
    listId = request.form['listId']
    currentUser = User.query.filter_by(username=session['user']).first()
    UsernameList.query.filter_by(id=listId, user_id=currentUser.id).delete()
    db.session.commit()
    return redirect(url_for('routes.toolHub'))

@routes.route('/addusernames', methods=['POST'])
def addUsernames():
    listId = int(request.form['listId'])
    fromAccount = request.form['fromaccount']

    # currentUser = User.query.filter_by(username=session['user']).first()
    listToUpdate = UsernameList.query.filter_by(id=listId).first()
    listContent = json.loads(listToUpdate.list)
    newListContent = listContent
    
    auto = Auto()

    usernames = auto.getUsernames(fromAccount)

    for usr in usernames:
        if usr not in listContent:
            newListContent.append(usr)

    listToUpdate.list = json.dumps(newListContent)
    
    db.session.commit()

    return redirect(url_for('routes.toolHub'))

@routes.route('/sendmessage', methods = ['POST'])
def sendMessage():
    message = request.form['message']
    listId = request.form['listId']
    currentUser = User.query.filter_by(username=session['user']).first()
    userList = UsernameList.query.filter_by(id=listId).first()
    listContent = json.loads(userList.list)

    auto = Auto()
    auto.loadCookies(json.loads(currentUser.cookies))

    auto.sendMessage(message, listContent)
    
    return redirect(url_for('routes.toolhub'))

InstaGrab/website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>{% block title%}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{{url_for('routes.home')}}">InstaGrab</a>
          </div>
          <ul class="nav navbar-nav">
            <li {% if active_page == 'home' %}class="active"{% endif %}><a href="{{ url_for('routes.home') }}">Home</a></li>
            <li {% if active_page == 'toolhub' %}class="active"{% endif %}><a href="{{ url_for('routes.toolHub') }}">Tool hub</a></li>
            <li {% if active_page == 'login' %}class="active"{% endif %}><a href="{{ url_for('routes.login') }}">Login</a></li>
            <li><a href="{{ url_for('routes.logout') }}">Logout</a></li>
        </ul>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <div class="alert error" role="alert">
              {{ message }}
            </div>
          {% else %}
            <div class="alert success" role="alert">
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock %}
  </body>
</html>

InstaGrab/website/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content%}
<div class="container">
    <h1>Welcome to Instagrab!</h1>
    <p>Connecting with your audience on Instagram just got easier.</p>
    <p>Instagrab is your ultimate solution for automating your Instagram outreach. Whether you're a marketer, influencer, or business owner, Instagrab empowers you to streamline your engagement process, saving you time and effort.</p>
    <h2>Why Choose Instagrab?</h2>
    <ul>
        <li>Effortless Connectivity: Seamlessly connect your Instagram account to Instagrab and unlock a world of possibilities.</li>
        <li>Powerful Scraping Tools: Gather username lists from various sources effortlessly. Whether it's hashtags, followers of a specific account, or custom lists, Instagrab's scraping tools have you covered.</li>
        <li>Tailored Messaging: Craft personalized messages and reach out to your audience en masse. Engage with potential customers, network with influencers, or simply connect with like-minded individuals.</li>
        <li>Automation Made Simple: Set up automated workflows to handle repetitive tasks, allowing you to focus on what truly matters—building relationships and growing your brand.</li>
        <li>Insightful Analytics: Gain valuable insights into your outreach efforts with Instagrab's comprehensive analytics. Track message delivery, response rates, and more to fine-tune your strategy and maximize your results.</li>
    </ul>
    <p>Get Started Today! Join thousands of satisfied users who have already revolutionized their Instagram outreach with Instagrab. Sign up now and take the first step towards a more efficient and effective social media presence.</p>
</div>
{% endblock %}

InstaGrab/website/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content%}
<h2 class="text-center">Login with your Instagram credentials</h2>
<form class="login-form" action="/login" method="post">
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" id="username" name="username" required>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-lg">Login</button>
    </div>
</form>
{% endblock %}

InstaGrab/website/templates/toolhub.html
{% extends 'base.html' %}

{% block title %}Tool Hub{% endblock %}

{% block content%}
<div class="lists-overview">
    <div class="listscrollmenu">
        <button class="scroll-btn left-btn">&#10094;</button>
        <div class="menu-container">
            <div class="menu">
                {% for list in data %}
                    <a href="#" class="list {{list['id']}}">{{ list['name'] }}</a>
                {% endfor %}
                <a title="New list" class="new-list-btn">+</a>
            </div>
        </div>
        <button class="scroll-btn right-btn">&#10095;</button>
    </div>
    <div class="list-displayer">
        {% for list in data %}
            <div class="list-display number{{list['id']}}" style="display: none;">
                {% for username in list['usernames'] %}
                    <p>{{username}}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
<div class="popup-bg new-list">
    <div class="popup-box">
        <form action="/newlist" method="post" class="name-list-form">
            <h2>Name your list</h2>
            <input type="text" id="listname" name="listname" required>
            <input type="submit" value="Submit">
        </form>
        <button class="cancel-new-list-btn">Cancel</button>
    </div>
</div>
<div class="popup-bg add-users">
    <div class="popup-box">
        <form action="/addusernames" method="post" class="add-users-form">
            <h2>Add usernames</h2>
            <label for="fromaccount">From followers of :</label>
            <input type="text" name="fromaccount">
            <input type="hidden" name="listId" id="list-id-input" required>
            <input type="submit" value="Submit">
        </form>
        <button class="cancel-add-users-btn">Cancel</button>
    </div>
</div>
<div class="popup-bg message">
    <div class="popup-box">
        <form action="/sendmessage" method="post" class="send-message-form">
            <h2>Send message</h2>
            <label for="message">Message :</label>
            <input type="text" name="message">
            <input type="hidden" name="listId" id="list-id-input" required>
            <input type="submit" value="Submit">
        </form>
        <button class="cancel-send-message-btn">Cancel</button>
    </div>
</div>
<div class="actions">
    <h2 class="actions-header">Actions</h2>
    <form action="/deletelist" method="post" class="action-container delete">
        <input type="hidden" name="listId" id="list-id-input" required>
        <button type="submit" class="actions-btn delete-list">Delete</button>
    </form>
    <div class="action-container add">
        <button class="actions-btn add-users">Add usernames</button>
    </div>
    <div class="action-container message">
        <button class="actions-btn send-message">Send message</button>
    </div>
</div>

<script src="{{ url_for('static', filename='toolHubScript.js') }}"></script>
{% endblock %}